version: '3.9'
services:
  web:
    image: node:lts
    user: 'node'
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    volumes:
      - ./:/home/node/app
    command: 'npm start'
volumes:
  individual-project: